"""remove unique constraint on sales journal_entry_id

Revision ID: 16855b650018
Revises: 92c72724bcbc
Create Date: 2026-02-11 08:14:25.936755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16855b650018'
down_revision: Union[str, Sequence[str], None] = '92c72724bcbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sales_journal_entry_id_key'), 'sales', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('sales_journal_entry_id_key'), 'sales', ['journal_entry_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
