"""add_supplier_and_purchase_order_tables

Revision ID: 1d46c9fd0948
Revises: 690bd909abd9
Create Date: 2026-02-11 07:26:45.151462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d46c9fd0948'
down_revision: Union[str, Sequence[str], None] = '690bd909abd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('vat_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RECEIVED', 'CANCELLED', name='postatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_po_status', 'purchase_orders', ['status'], unique=False)
    op.create_index('ix_po_supplier', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('po_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_po_items_po', 'purchase_order_items', ['po_id'], unique=False)
    op.create_index('ix_po_items_product', 'purchase_order_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_po_items_product', table_name='purchase_order_items')
    op.drop_index('ix_po_items_po', table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index('ix_po_supplier', table_name='purchase_orders')
    op.drop_index('ix_po_status', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
