"""Initial_schema_accounting_and_users

Revision ID: 241b1f12e416
Revises: 
Create Date: 2026-02-11 05:41:22.632359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '241b1f12e416'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype'), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_accounts_code', 'accounts', ['code'], unique=False)
    op.create_index('ix_accounts_type', 'accounts', ['account_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ACCOUNTANT', 'CASHIER', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_table_record', 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journal_entries_date', 'journal_entries', ['entry_date'], unique=False)
    op.create_table('transaction_splits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.CheckConstraint('(debit_amount > 0 AND credit_amount = 0) OR (credit_amount > 0 AND debit_amount = 0)', name='ck_split_debit_xor_credit'),
    sa.CheckConstraint('credit_amount >= 0', name='ck_split_credit_non_negative'),
    sa.CheckConstraint('debit_amount >= 0', name='ck_split_debit_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_splits_account', 'transaction_splits', ['account_id'], unique=False)
    op.create_index('ix_splits_journal', 'transaction_splits', ['journal_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_splits_journal', table_name='transaction_splits')
    op.drop_index('ix_splits_account', table_name='transaction_splits')
    op.drop_table('transaction_splits')
    op.drop_index('ix_journal_entries_date', table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index('ix_audit_table_record', table_name='audit_logs')
    op.drop_index('ix_audit_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_index('ix_accounts_type', table_name='accounts')
    op.drop_index('ix_accounts_code', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
