"""add_quotes_and_quote_items

Revision ID: 5964ccfd67f3
Revises: 9cdf802d74b8
Create Date: 2026-02-11 19:01:41.259028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5964ccfd67f3'
down_revision: Union[str, Sequence[str], None] = '9cdf802d74b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quote_number', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_vat', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'CONVERTED', name='quotestatus'), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_number')
    )
    op.create_index('ix_quotes_created_at', 'quotes', ['created_at'], unique=False)
    op.create_index('ix_quotes_created_by', 'quotes', ['created_by'], unique=False)
    op.create_index('ix_quotes_number', 'quotes', ['quote_number'], unique=False)
    op.create_index('ix_quotes_status', 'quotes', ['status'], unique=False)
    op.create_table('quote_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_items_product', 'quote_items', ['product_id'], unique=False)
    op.create_index('ix_quote_items_quote', 'quote_items', ['quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quote_items_quote', table_name='quote_items')
    op.drop_index('ix_quote_items_product', table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_index('ix_quotes_status', table_name='quotes')
    op.drop_index('ix_quotes_number', table_name='quotes')
    op.drop_index('ix_quotes_created_by', table_name='quotes')
    op.drop_index('ix_quotes_created_at', table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
