"""add_credit_notes_and_shrinkage

Revision ID: 9cdf802d74b8
Revises: 16855b650018
Create Date: 2026-02-11 17:12:16.182772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cdf802d74b8'
down_revision: Union[str, Sequence[str], None] = '16855b650018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_journal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('credit_note_number', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', name='creditnotestatus'), nullable=False),
    sa.Column('total_refund_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('vat_refund_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('net_refund_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['original_journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_note_number')
    )
    op.create_index('ix_credit_notes_created_at', 'credit_notes', ['created_at'], unique=False)
    op.create_index('ix_credit_notes_original_je', 'credit_notes', ['original_journal_entry_id'], unique=False)
    op.create_index('ix_credit_notes_status', 'credit_notes', ['status'], unique=False)
    op.create_table('credit_note_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('credit_note_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('RESALABLE', 'DAMAGED', name='itemcondition'), nullable=False),
    sa.Column('unit_refund_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('line_refund_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_note_items_cn', 'credit_note_items', ['credit_note_id'], unique=False)
    op.create_index('ix_credit_note_items_product', 'credit_note_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credit_note_items_product', table_name='credit_note_items')
    op.drop_index('ix_credit_note_items_cn', table_name='credit_note_items')
    op.drop_table('credit_note_items')
    op.drop_index('ix_credit_notes_status', table_name='credit_notes')
    op.drop_index('ix_credit_notes_original_je', table_name='credit_notes')
    op.drop_index('ix_credit_notes_created_at', table_name='credit_notes')
    op.drop_table('credit_notes')
    # ### end Alembic commands ###
